-- MySQL Script generated by MySQL Workbench
-- Tue May  9 23:56:57 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cve
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cve
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cve` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `cve` ;

-- -----------------------------------------------------
-- Table `cve`.`fixed`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cve`.`fixed` ;

CREATE TABLE IF NOT EXISTS `cve`.`fixed` (
  `id` VARCHAR(255) NOT NULL,
  `fecha` DATETIME(6) NULL DEFAULT NULL,
  `severity` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cve`.`vulnerabilities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cve`.`vulnerabilities` ;

CREATE TABLE IF NOT EXISTS `cve`.`vulnerabilities` (
  `id` VARCHAR(255) NOT NULL,
  `base_severity` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(2550) NULL DEFAULT NULL,
  `last_modified` DATETIME(6) NULL DEFAULT NULL,
  `published` DATETIME(6) NULL DEFAULT NULL,
  `vuln_status` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
